apps/trips/urls.py
from django.urls import path

from .views import *

app_name = 'trips'
urlpatterns = [
    path('detail/<str:trip_id>/', show_trip, name='show_trip'),
    path('new_manual/<int:route_id>', new_trip_manual, name='new_trip_manual'),
    path('new_file/<int:route_id>', new_trip_file, name='new_trip_file'),
    path('api/new', new_trip_api, name='new_trip_api'),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

from django.conf.urls.static import static

urlpatterns = [
    
    path('', include('apps.gtfs.urls'), name='gtfs'),

    path('routes/', include('apps.routes.urls'), name='routes'),
    path('trips/', include('apps.trips.urls'), name='trips'),
    path('stops/', include('apps.stops.urls'), name='stops'),
    path('shapes/', include('apps.shapes.urls'), name='shapes'),
    path('stop_times/', include('apps.stop_times.urls'), name='stop_times'),

    path('admin/', admin.site.urls),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/trips/models.py
from django.db import models

from apps.routes.models import Routes
from apps.shapes.models import Shapes

class Trips(models.Model):
    route = models.ForeignKey(Routes, models.DO_NOTHING, blank=True, null=True)
    service_id = models.CharField(max_length=30, blank=True, null=True)
    trip_id = models.CharField(primary_key=True, max_length=20)
    trip_short_name = models.CharField(max_length=50, blank=True, null=True)
    trip_headsign = models.CharField(max_length=100, blank=True, null=True)
    direction_id = models.SmallIntegerField(blank=True, null=True)
    block_id = models.IntegerField(blank=True, null=True)
    shape_id = models.CharField(max_length=20, blank=True, null=True)
    shape_id_serial = models.ForeignKey(Shapes, models.DO_NOTHING, db_column='shape_id_serial', blank=True, null=True)
    bikes_allowed = models.SmallIntegerField(blank=True, null=True)
    wheelchair_accessible = models.SmallIntegerField(blank=True, null=True)
    trip_type = models.IntegerField(blank=True, null=True)
    drt_max_travel_time = models.IntegerField(blank=True, null=True)
    drt_avg_travel_time = models.IntegerField(blank=True, null=True)
    drt_advance_book_min = models.IntegerField(blank=True, null=True)
    drt_pickup_message = models.IntegerField(blank=True, null=True)
    drt_drop_off_message = models.IntegerField(blank=True, null=True)
    continuous_pickup_message = models.CharField(max_length=50, blank=True, null=True)
    continuous_drop_off_message = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'trips'
        verbose_name_plural = "trips"

    def __str__(self):
        from apps.stop_times.models import StopTimes

        stop_times = StopTimes.objects.filter(trip = self.trip_id).order_by('stop_sequence')

        return "{} - T{} ({} - {})".format(self.route.route_long_name, self.trip_id[2:8], stop_times[0].departure_time, stop_times.order_by('-stop_sequence')[0].departure_time)

apps/trips/forms.py
from django import forms
from django.forms import ModelForm

from apps.trips.models import Trips

class GPS_file_form(forms.Form):
    file = forms.FileField(label='Selecione o arquivo do GPS')

class TripForm(forms.ModelForm):
    class Meta:
        model = Trips
        fields = [
            'route',
            'trip_id', 
            'service_id',
            'trip_short_name', 
            'trip_headsign',
            'shape_id',
        ]
        labels = {
            "route": "Rota",
            "trip_id": "ID do Trajeto (Autogerado)", 
            "service_id": "Serviço (Autogerado)",
            "trip_short_name": "Short Name (Opcional)", 
            "trip_headsign": "Nome no Visor (Opcional)",
            "shape_id": "Shape (Já associada ao Trajeto)",
        }

apps/trips/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.csrf import ensure_csrf_cookie
from django.http import HttpResponse, JsonResponse

from .forms import GPS_file_form, TripForm

from apps.gtfs.helpers.coordinates import shape_midpoint, shape_midpoint_dict
from apps.gtfs.helpers.handle_uploads import handle_uploaded_file
from apps.gtfs.helpers.gps2gtfs.KML_helper import KML
from apps.stops.helpers import paradas_proximas

from apps.trips.models import Trips
from apps.routes.models import Routes
from apps.shapes.models import Shapes
from apps.stops.models import Stops
from apps.stop_times.models import StopTimes


@login_required
def show_trip(request, trip_id):

    trip = get_object_or_404(Trips, trip_id=trip_id)
    route = get_object_or_404(Routes, route_id = trip.route_id)
    
    shapes = Shapes.objects.filter(shape_id = trip.shape_id).order_by('shape_pt_sequence')
    midpoint = shape_midpoint(shapes)

    stop_times = StopTimes.objects.filter(trip = trip.trip_id)

    context = {
        'title' : 'Trajeto {}'.format(trip.trip_id[2:8]),
        'trip': trip,
        'route': route,
        'shapes': shapes,
        'stop_times': stop_times,
        'first_stop': stop_times[0],
        'last_stop': stop_times.order_by('-stop_sequence')[0],
        'midpoint': '[ {}, {} ]'.format(midpoint[0], midpoint[1]),
    }

    return render(request,'trips/show/show_trip.html', context)

@login_required
def new_trip_manual(request, route_id):
    context = {
        'title' : 'Nova Trip - Manual',
    }

    return render(request,'trips/new/new_trip_manual.html', context)

@login_required
def new_trip_file(request, route_id):

    if request.method == 'POST' and ('file' in request.FILES):
        filename = request.FILES.get('file').name

        extensoes_suportadas = ['.kml']
        if any(ext in filename for ext in extensoes_suportadas):

            new_file = handle_uploaded_file(request.FILES.get('file'), request.user)

            last_shape = Shapes.objects.filter(shape_id__startswith='p_').order_by('-shape_id')[0].shape_id

            context = {}
            if filename.endswith('.kml'):
                context['stop_times'], context['shapes'] = KML(new_file)

            new_trip_id = '{}{}{}'.format('t_', int(Trips.objects.all().order_by('-trip_id')[0].trip_id[2:8]) + 1, '_b_6309_tn_0')
            
            temp_trip = Trips(
                trip_id = new_trip_id,
                service_id = 'c_5988_b_6309_d_31',
                shape_id = 'p_{}'.format(int(last_shape[2:]) + 1)
            )
            
            route = Routes.objects.filter(route_id = route_id)

            if route: temp_trip.route = route[0]

            context['trip_form'] = TripForm(instance = temp_trip)
            context['trip'] = temp_trip
            context['last_shape'] = context['shapes'][-1]['shape_pt_sequence']

            context['horario_inicio'] = context['stop_times'][0]['arrival_time']
            
            context['midpoint'] = shape_midpoint_dict(context['shapes'])

            context['title'] = 'Nova Trip - Formulário de Validação'

            for stop in context['stop_times']:
                stop['paradas_proximas'] = paradas_proximas(stop['stop']['stop_lat'], stop['stop']['stop_lon'])

            return render(request,'trips/new/new_trip_scratch.html', context)

        else: 
            messages.error(request, 'Formato de arquivo inválido! Confira a lista com formatos permitidos')


    context = {
        'title' : 'Nova Trip - Arquivo',
        'route_id': route_id
    }

    return render(request,'trips/new/new_trip_file_upload.html', context)

@ensure_csrf_cookie
def new_trip_api(request):
    if not request.user.username:
        return JsonResponse({'Erro': 'Não autorizado' }, status=403)

    if request.method == 'POST':

        route = Routes.objects.get(route_id = int(request.POST['route']))

        trip = Trips (
            route = route,
            trip_id = request.POST['trip_id'],
            service_id = request.POST['service_id'],
            trip_short_name = request.POST['trip_short_name'],
            trip_headsign = request.POST['trip_headsign'],
            shape_id =request.POST['shape_id']
        ).save()

        return JsonResponse({
            'Sucesso': 'Trip criada com sucesso!'
        })

    return JsonResponse({ 'Erro': 'Aceitamos apenas POST' })

templates/trips/forms/_new_trip_form.html
{% load widget_tweaks %}

<p> Informações Gerais </p>

{% csrf_token %}

{% for field in trip_form %}


<div class="form-group form-inline">

    <!-- <div class="row col-12"> -->

    <!-- <div class="col-6">  -->

    <label> {{ field.label }} </label>

    {{ field|add_class:'form-control' }}

    <!-- </div> -->

    <!-- </div> -->

</div>

{% endfor %}

<div id="data-shapes" class="d-none">
    [
    {% for shape in shapes %}
    {
    "shape_pt_lon": {{ shape.shape_pt_lon }},
    "shape_pt_lat": {{ shape.shape_pt_lat }},
    "shape_pt_sequence": {{ shape.shape_pt_sequence }},
    "shape_id": "{{ trip.shape_id }}"
    }

    {% if not shape.shape_pt_sequence == last_shape %}
    ,
    {% endif %}


    {% endfor %}
    ]
</div>

templates/trips/forms/file_upload_form.html
{% load widget_tweaks %}

<form enctype="multipart/form-data" action="{% url 'trips:new_trip_file' route_id %}" method="POST" class="form-group mw-full">
    
    <div class="card row">
        <div class="col-8">
            <div class="text-center">
                <br>
                {% csrf_token %}
        
                <div class="custom-file">
                    <input type="file" id="file" name="file">
                    <label for="file"> Selecione o arquivo de GPS </label>
                </div>
            </div>
        </div>
    
        <div class="col-4">
            <div class="">
                <p> Tipos de arquivo suportados: </p>
        
                <ul>
                    <li class="badge badge-pill badge-success text-white"> .KML </li> <small class="ml-5"> Formato disponível </small> <br>
                    <li class="badge badge-pill disabled"> .GPX </li> <small class="text-danger ml-5"> Formato ainda não disponível </small> <br>
                    <li class="badge badge-pill disabled"> .KMZ </li> <small class="text-danger ml-5"> Formato ainda não disponível </small> <br>
                </ul>
            </div>
        </div>
    </div>

    <div class="row card">
        <div class="col-6">
            <a class="btn btn-danger" href="{% url 'dashboard' %}">
                Voltar para a Home
            </a>
        </div>

        <div class="col-6 text-right">
            <input class="btn btn-success text-white" type="submit" value="Upload" />
        </div>
    </div>

</form>