apps/routes/urls.py
from django.urls import path

from .views import *

app_name = 'routes'
urlpatterns = [
    path('', index, name='index'),
    path('new', new_route, name='new_route'),
    path('<int:route_id>', show_route, name='show_route'),
    path('<int:route_id>/edit', edit_route, name='edit_route'),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

from django.conf.urls.static import static

urlpatterns = [
    
    path('', include('apps.gtfs.urls'), name='gtfs'),

    path('routes/', include('apps.routes.urls'), name='routes'),
    path('trips/', include('apps.trips.urls'), name='trips'),
    path('stops/', include('apps.stops.urls'), name='stops'),
    path('shapes/', include('apps.shapes.urls'), name='shapes'),
    path('stop_times/', include('apps.stop_times.urls'), name='stop_times'),

    path('admin/', admin.site.urls),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/routes/models.py
from django.db import models

from apps.agency.models import Agency

class Routes(models.Model):
    agency = models.ForeignKey(Agency, models.DO_NOTHING, blank=True, null=True)
    route_id = models.IntegerField(primary_key=True)
    route_short_name = models.CharField(max_length=50, blank=True, null=True)
    route_long_name = models.CharField(max_length=255, blank=True, null=True)
    route_desc = models.CharField(max_length=255, blank=True, null=True)
    route_type = models.SmallIntegerField(blank=True, null=True)
    route_url = models.CharField(max_length=50, blank=True, null=True)
    route_color = models.CharField(max_length=11, blank=True, null=True)
    route_text_color = models.CharField(max_length=11, blank=True, null=True)
    route_sort_order = models.IntegerField(blank=True, null=True)
    min_headway_minutes = models.IntegerField(blank=True, null=True)
    eligibility_restricted = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'routes'
        verbose_name_plural = "routes"

    def __str__(self):
        return '{} - {}'.format(self.route_id, self.route_long_name)

apps/routes/forms.py
from django.db import models
from django.forms import ModelForm

from apps.routes.models import Routes

class RoutesForm(ModelForm):
    class Meta:
        model = Routes
        fields = [
            'route_id', 
            'route_short_name', 
            'route_long_name',
            'route_type',
            'route_color'
        ]

        # widgets = {
        #     'route_id': Textarea(attrs={'': 80, 'rows': 20}),
        # }

apps/routes/admin.py
from django.contrib import admin

from .models import *

admin.site.register(Routes)

apps/routes/apps.py
from django.apps import AppConfig


class RoutesConfig(AppConfig):
    name = 'routes'

apps/routes/tests.py
from django.test import TestCase

# Create your tests here.

apps/routes/views.py
from django.shortcuts import render, redirect
from  django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required

import unidecode

from apps.routes.forms import RoutesForm

from apps.routes.models import Routes
from apps.trips.models import Trips

ROUTES_PER_PAGE = 15

@login_required
def index(request):
    rotas = Routes.objects.order_by('route_long_name')
    query = request.GET.get('q')
    
    if query:
        query_unicode = unidecode.unidecode(query)

        rotas = rotas.filter(
            Q(route_long_name__icontains=query) | Q(route_long_name__icontains=query_unicode)
        )
    
    paginator = Paginator(rotas, ROUTES_PER_PAGE)
    page = request.GET.get('page')
    rotas_pag = paginator.get_page(page)

    context = {
        'title' : 'Rotas',
        'prev_url': 'dashboard',
        'routes' : rotas_pag,
        'query': query
    }

    return render(request,'routes/routes.html', context)

@login_required
def show_route(request, route_id):
    route = get_object_or_404(Routes, route_id=route_id)

    trips = Trips.objects.all().filter(route = route_id)

    context = {
        'title' : 'Rota {}'.format(route.route_id),
        'prev_url': 'routes:index',
        'route' : route,
        'trips': trips
    }

    return render(request,'routes/show/show_route.html', context)

@login_required
def new_route(request):

    if request.method == 'POST':
        form = RoutesForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request,'Rota criada com sucesso!')

            return redirect('routes:show_route', form.cleaned_data['route_id'])

        else:
            messages.error(request,'Ocorreu um erro ao criar a Rota')
            form = RoutesForm()
    else:
        form = RoutesForm()

    context = {
        'title' : 'Criar uma Rota',
        'form': form
    }

    return render(request,'routes/new/new_route.html', context)

@login_required
def edit_route(request, route_id):
    route = get_object_or_404(Routes, route_id=route_id)

    if request.method == 'POST':
        form = RoutesForm(request.POST, instance = route)

        if form.is_valid():
            form.save()
            messages.success(request,'Rota alterada com sucesso!')

            return redirect('routes:show_route', route_id)
        else:
            form = RoutesForm(instance = route)
    else:
        form = RoutesForm(instance = route)

    context = {
        'title' : 'Editar a Rota {}'.format(route.route_id),
        'form': form,
        'route' : route,
    }

    return render(request,'routes/edit/edit_route.html', context)

templates/routes/partials/_item_simple.html
<th> <spam style="color: #{{ route.route_color }};" > ⦿ &nbsp; </spam> {{ route.route_long_name }}</th>

templates/routes/partials/_item_table.html
<tr>
    <th> <spam style="color: #{{ route.route_color }};" > ⦿ &nbsp; </spam> {{ route.route_long_name }}</th>
    <th> 
        <div class="float-right">
            <a class="btn" href="{% url 'routes:show_route' route.route_id %}">
                <i class="fa fa-eye" aria-hidden="true"></i>
            </a>
            <a class="btn" href="{% url 'routes:edit_route' route.route_id %}">
                <i class="fa fa-pencil" aria-hidden="true"></i>
            </a>
        </div>
    </th>
</tr>

templates/routes/partials/_pagination.html
<!-- <p class="float-right"> Na página: {{ routes|length }} rotas </p> -->

<div align="center"> 

    <section class="top-catagory-area section-padding-20-0">
        <div class="container">

            {% if routes.has_other_pages %}
            <ul class="pagination">
                {% if routes.has_previous %}
                <li class="page-item">
                    <a href="?page={{ routes.previous_page_number }}" class="page-link">&laquo;</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">&laquo;</a>
                </li>
                {% endif %}
                {% for pagina in routes.paginator.page_range %}
                {% if routes.number == pagina %}
                <li class="page-item active">
                    <a class="page-link">{{ pagina }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a href="?page={{pagina}}" class="page-link">{{pagina}}</a>
                </li>
                {% endif %}
                {% endfor %}
                {% if routes.has_next %}
                <li class="page-item">
                    <a href="?page={{ routes.next_page_number }}" class="page-link">&raquo;</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">&raquo;</a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </section>

</div>

templates/routes/partials/_table.html
<table class="table table-hover">

    <tbody>

        {% for route in routes %}

        {% include 'routes/partials/_item_table.html' %}

        {% endfor %}

    </tbody>

</table>
<br>